### ISSUE TITLE
Database Design and Integration

### ISSUE THREAD

**Issue by 0wlie22** [0wlie22/helix#2]
Design the database schema for storing data:
- table of usernames and points
- table of user terms, definitions, coefficient of mastery, right answers, total answers

Interactions with database:
- getting terms and their definitions from the database
- storing the coefficient of the term
- storing user points

**Comment by TheCrabilia** [comment]
![Untitled](https://github.com/user-attachments/assets/9bd138dd-c976-4d43-adf6-a0d7023d4ce9)
